version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: grandslam
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: root
      MYSQL_PASSWORD: heroes24
    ports:
      - 3306:3306

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379